	# cd to script dir
if {[info tclversion] >= 8.4} {
    set scriptDir [file normalize [file dirname [info script]]]
} else {
    append scriptDir [pwd] / [file dirname [info script]]
}; # if
cd $scriptDir


set timeout 2


	# Test single file configuration

	# Start bash
exp_spawn bash --rcfile bashrc
set prompt "cdots@/"
expect -ex $prompt
	# Load scripts
send "source ../../cdots.sh\n"
	# Execute tests
source lib/tests.exp
send "\rexit\r"

	# Test split file configuration

    # Make sure previous test is closed
exp_close; exp_wait
	# Start bash
exp_spawn bash --rcfile bashrc
set prompt "cdots@/"
expect -ex $prompt> 
	# Load scripts
send "source ../../cdots-functions.sh\n"
send "source ../../cdots-completion.sh\n"
	# Execute tests
source lib/tests.exp
send "\rexit\r"
