	# cd to script dir
set scriptDir [file normalize [file dirname [info script]]]
cd $scriptDir


set timeout 2


	# Test single file configuration

	# Start bash
exp_spawn bash --rcfile bashrc
set prompt "bashdots@/"
expect -re $prompt> 
	# Load scripts
send "source ../../cdots.sh\n"
	# Execute tests
source lib/tests.exp
send "\nexit\n"

	# Test split file configuration

	# Start bash
exp_spawn bash --rcfile bashrc
set prompt "bashdots@/"
expect -re $prompt> 
	# Load scripts
send "source ../../cdots-functions.sh\n"
send "source ../../cdots-completion.sh\n"
	# Execute tests
source lib/tests.exp
send "\nexit\n"
