    # Use bash strict mode
set -o posix
	# Set prompt to ignore current working directory; display path starting from here
	# E.g. prompt: bashdots//fixture1/1-1>
mwd=$(pwd)
PS1='bashdots@$(cwd=$(pwd); echo ${cwd//$mwd//})>'
	# Configure readline
INPUTRC=$(pwd)/inputrc
	# Ensure enough columns so expect doesn't have to care about line breaks
stty columns 150


function clearDots() {
    local dots=. dotsFunctions dotsAliases DOTS_DEPTH=7
    for ((i = 1; i <= $DOTS_DEPTH; i++)); do
        dotsFunctions="$dotsFunctions dots$(($i + 1))"
        dots=$dots.
            # Unset alias
        alias $dots > /dev/null 2>&1 && unalias $dots
    done
        # Unset functions
    unset -f $dotsFunctions
        # Unset completion
    complete -r $dotsFunctions &> /dev/null
} # clearDots()


clearDots
