set DEPTH 8


set dirs ""
set dots .
for {set i 1} {$i < $DEPTH} {incr i} {
	set test "${i}up with argument - non-existing-dir"
	set dir "$i-1"
	set dots $dots.
  		# Previous working directory
	set pwd [join $dirs "/"];
 	if [llength $dirs] {
		set pwd $pwd/
	}; # if
	set dirs [concat $dirs $dir]
	set cwd  [join $dirs "/"]
	send "cd $scriptDir/fixture1/$cwd\r"
	expect -re $prompt/fixture1/$cwd>
		# Send command
	set cmd "$dots non_existing_dir"
	send "$cmd\r"
		# Bash should've stayed in the same directory
	set expected "^$cmd\r\nbash: cd: .*$prompt/fixture1/$cwd>$"
	expect {
		-re $expected { pass $test }
		-re $prompt.*> { fail "$test at prompt (expected '$expected', output: '$expect_out(buffer)'" }
		eof       { fail "$test at eof" }
		timeout   { fail "$test at timeout" }
	}; # expect
}; # for



set dirs ""
set dots .
for {set i 1} {$i < $DEPTH} {incr i} {
	set test "${i}up without argument"
	set dir "$i-1"
	set dots $dots.
  		# Previous working directory
	set pwd [join $dirs "/"];
 	if [llength $dirs] {
		set pwd $pwd/
	}; # if
	set dirs [concat $dirs $dir]
	set cwd  [join $dirs "/"]
	send "cd $scriptDir/fixture1/$cwd\r"
	expect -re $prompt/fixture1/$cwd>
		# Send command
	set cmd "$dots"
	send "$cmd\r"
	set expected "^$cmd\r\n$prompt/fixture1>$"
	expect {
		-re $expected { pass $test }
		-re $prompt.*> { fail "$test at prompt (expected '$expected', output: '$expect_out(buffer)'" }
		eof       { fail "$test at eof" }
		timeout   { fail "$test at timeout" }
	}; # expect
}; # for


set dirs ""
set dots .
for {set i 1} {$i < $DEPTH} {incr i} {
	set test "${i}up with completion of filled argument"
	set dir  "$i-1"
	set dots $dots.
  		# Previous working directory
	set pwd [join $dirs "/"];
 	if [llength $dirs] {
		set pwd $pwd/
	}; # if
	set dirs [concat $dirs $dir]
	set cwd  [join $dirs "/"]
	send "cd $scriptDir/fixture1/$cwd\r"
	expect -re $prompt/fixture1/$cwd>
		# Try completion
	set cmd "$dots ${pwd}$i-"
	send "$cmd\t"
	set expected "^$cmd\r\n$i-1/ +$i-2/ +\r\n$prompt/fixture1/$cwd>$cmd$"
	expect {
		-re $expected  { pass "$test" }
		-re $prompt.*> { fail "$test at prompt (expected '$expected', output: '$expect_out(buffer)'" }
		eof       { fail "$test at eof" }
		timeout   { fail "$test at timeout" }
	}; # expect


	set test "${i}upped with argument-completion"
		# Try to really cd
	send "1\n"
	set expected $prompt/fixture1/$cwd>
	expect {
		-re $expected    { pass "$test" }
		-re $prompt.*>   { fail "$test at prompt (expected '$expected', output: '$expect_out(buffer)'" }
		eof              { fail "$test at eof" }
		timeout          { fail "$test at timeout" }
	}; # expect
}; # for



set dirs ""
set dots .
for {set i 1} {$i < $DEPTH} {incr i} {
	set test "${i}up with completion of empty argument"
	set dir  "$i-1"
	set dots $dots.
  		# Previous working directory
	set pwd [join $dirs "/"];
 	if [llength $dirs] {
		set pwd $pwd/
	}; # if
	set dirs [concat $dirs $dir]
	set cwd  [join $dirs "/"]
	send "cd $scriptDir/fixture1/$cwd\r"
	expect -re $prompt/fixture1/$cwd>
		# Try completion
	set cmd "$dots "
	send "$cmd\t"
	set expected "^$cmd\r\n1-1/ +1-2/ +.svn/ *\r\n$prompt/fixture1/$cwd>$cmd$"
	expect {
		-re $expected  { pass "$test" }
		-re $prompt.*> { fail "$test at prompt (expected '$expected', output: '$expect_out(buffer)'" }
		eof       { fail "$test at eof" }
		timeout   { fail "$test at timeout" }
	}; # expect


	set test "${i}upped with argument-completion"
		# Try to really cd
	send "1\n"
	set expected $prompt/fixture1/$cwd>
	expect {
		-re $expected    { pass "$test" }
		-re $prompt.*>   { fail "$test at prompt (expected '$expected', output: '$expect_out(buffer)'" }
		eof              { fail "$test at eof" }
		timeout          { fail "$test at timeout ($expect_out(buffer))" }
	}; # expect
}; # for



set dirs ""
set dots .
for {set i 1} {$i < $DEPTH} {incr i} {
	set test "${i}up with completion of path argument"
	set dir  "$i-1"
	set dots $dots.
  		# Previous working directory
	set pwd [join $dirs "/"];
 	if [llength $dirs] {
		set pwd $pwd/
	}; # if
	set dirs [concat $dirs $dir]
	set cwd  [join $dirs "/"]
	send "cd $scriptDir/fixture1/$cwd\r"
	expect -re $prompt/fixture1/$cwd>
		# Try completion
	set cmd "$dots $pwd"
	send "$cmd\t"
	set expected "^$cmd\r\n$i-1/ +$i-2/ +\.svn/ *\r\n$prompt/fixture1/$cwd>$cmd$"
	expect {
		-re $expected  { pass "$test" }
		-re $prompt.*> { fail "$test at prompt (expected '$expected', output: '$expect_out(buffer)'" }
		eof       { fail "$test at eof" }
		timeout   { fail "$test at timeout ($expect_out(buffer))" }
	}; # expect


	set test "${i}upped with argument-completion"
		# Try to really cd
	send "$i-1\n"
	#set expected $prompt/fixture1/$cwd/$i-1>
	set expected .*>
	expect {
		-re $expected    { pass "$test" }
		-re $prompt.*>   { fail "$test at prompt (expected '$expected', output: '$expect_out(buffer)'" }
		eof              { fail "$test at eof" }
		timeout          { fail "$test at timeout" }
	}; # expect
}; # for



set dirs ""
set dots .
for {set i 1} {$i < $DEPTH} {incr i} {
	set test "${i}up with completion of filled argument containing space"
	set dir  "{$i 1}"
	set dots $dots.
  		# Previous working directory
	set pwd [join $dirs "/"];
 	if [llength $dirs] {
		set pwd $pwd/
	}; # if
	set dirs [concat $dirs $dir]
	set cwd  [join $dirs "/"]
	send "cd '$scriptDir/fixture3/$cwd'\r"
	expect -re $prompt/fixture3/$cwd>
		# Try completion
	set cmd "$dots '${pwd}'$i\\ "
	send "$cmd\t"
        # Escape backslashes for regexp (\ -> \B)
    set cmd [string replace $cmd [string first "\\" $cmd] [string last "\\" $cmd] "\\B"]
	set expected "$cmd\r\n$i 1/  $i 2/  \r\n$prompt/fixture3/$cwd>"
	expect {
		-re $expected  { pass "$test" }
		-re $prompt.*> { fail "$test at prompt (expected '$expected', output: '$expect_out(buffer)'" }
		eof       { fail "$test at eof" }
		timeout   { fail "$test at timeout" }
	}; # expect


	set test "${i}upped with argument-completion"
		# Try to really cd
	send "1\n"
	set expected $prompt/fixture3/$cwd>
	expect {
		-re $expected    { pass "$test" }
		-re $prompt.*>   { fail "$test at prompt (expected '$expected', output: '$expect_out(buffer)'" }
		eof              { fail "$test at eof" }
		timeout          { fail "$test at timeout" }
	}; # expect
}; # for
